# Refer to Hydra documentation for more information about config group defaults.
# - https://hydra.cc/docs/tutorials/basic/your_first_app/defaults/
# - https://hydra.cc/docs/patterns/configuring_experiments/

defaults:
  #- datasets: scannet_v02_2cm
  #- datasets: nyu_v2
  
  - datasets: semantic_kitti
  #- models: gaussianformer
  
  - models: symphonies
  #- models: symphonies_sparseocc
  #- pretrained_model: symphonies
  - schedules: adamw_lr2e-4_30e
  #
  - _self_

hydra:
  mode: MULTIRUN  # refer to https://github.com/Lightning-AI/lightning/pull/11617
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M}

trainer:
  devices: 4
  accelerator: gpu
  #strategy: ddp
  sync_batchnorm: True
  # precision: 16-mixed
  

ckpt_path: outputs/smooth_0.05/e3_miou0.1493.ckpt #outputs/128x128x16_stage2/e5_miou0.1483.ckpt  #outputs/origin_sym/e28_miou0.1459.ckpt #outputs/stage1:lr5no_smooth_Stage2:lr0.002_smooth/e23_miou0.1475.ckpt
path: outputs/SemanticKITTI
voxel_backbone: symphonies
pre_trained_weights: outputs/SemanticKITTI_8cm/e27_miou0.1604.ckpt
phase: stage_1